### PR TITLE
gettext bug fix

### PR DESCRIPTION
**Pull request by cosme12**
#275 fixed.

Thanks for teaching.

### CODE REVIEW

**Comment by mwaclawek** [comment]
Thanks :) In line 30, there's a second occurrence that we could fix. It probably works right now (due to the dot), but it would be cleaner :) Could you add it?

**Comment by cosme12** [comment]
Added a few more. Check it.

**Comment by mwaclawek** [comment]
Thanks, looks good :)

It's definitely cleaner now, but what was actually happening before? Were these parts just dropped?

**Comment by cosme12** [comment]
Nop, most of them were followed by an ```m``` so nothing happens. If it were an ```s or d``` it could fail. But you wanted it "cleaner" so there you have :D

**Comment by mwaclawek** [comment]
Yes, it's perfect :) Thanks!

**Comment by cosme12** [comment]
There is a problem now. You can see the double %%

**Comment by mwaclawek** [comment]
Sorry, I think this was my mistake.

We only write `_(...)` (single underscore) functions in that text file and execute them later via `eval(...)`. Now it seems `%` doesn't have any special meaning in gettext and can just be used without escaping. It's `__(...)` (double underscore) and the underlying PHP function `sprintf(...)` where the `%` has a special meaning and must thus be escaped as `%%`.

On the other hand, then, why did we have problems with `%` in that file if it doesn't have a special meaning and doesn't need to be escaped?

The original string where the problems occurred was `10% s`. So maybe there's something else that was wrong with that phrase, as we don't call any function here that puts in replacements.

**Pull request merged**
