### PR TITLE
Button css not being displayed

### PR DESCRIPTION
**Pull request by cosme12**
You can see this when someone sends you a testspiele request. Button is inside a form not a link. You also change the file "number" when updating css, not sure why, but you will have to do it here too.

### CODE REVIEW

**Comment by mwaclawek** [comment]
Thank you!

 1. Could you attach a screenshot? Sorry, but I can't check this myself right now, because the period for friendly matches is over alreay in the live game ;)
 2. In the first instance, you added declarations for a `<button />` tag and in the following two instances, you changed the declarations from a `<button />` tag to an `<a />` tag with `class="button"`. Was this intentional? Don't we even need those declarations that you changed in the second and third instance? Maybe we should *add* (not *replace*) the new rule if we really need it?
 3. Changing that number parameter after the CSS file is necessary so that each user's browser knows there's some new CSS and fetches it form the server again. Hitting the refresh button or clearing the cache helps as well, but we can't force users to do so.

**Comment by cosme12** [comment]
Right, we should add insteed of remove. Not sure where is it used but just in case.
button

**Comment by mwaclawek** [comment]
Could you modify lines 661 and 686 of your pull request to *add* those selectors instead of replacing them? Then we could merge :)

**Comment by cosme12** [comment]
Fixed. Now my question is: what's the point of having ```a.button``` and ```button```. Does ```button``` take effect for all button tags including ```a.button, form.button``` and all of them?

**Comment by mwaclawek** [comment]
Thank you :) Have you tested this again? That is, does it display correctly now on the page for the friendly matches?

 * The CSS selector `button` just matches HTML tags of the form `<button />`.
 * The CSS selector `a.button` matches HTML tags of the form `<a class="button" />`.
 * The CSS selector `input` matches HTML tags of the form `<input />`, specifically `<input type="submit" />`.

For the first and last one, we always want them to look the same, usually. And sometimes, we even want to make a link look like a button -- that's what the second one is for.

**Comment by cosme12** [comment]
This is how it looks now.
button
Where do we use ```a.button``` in the code?

**Comment by mwaclawek** [comment]
Looks perfect, thanks :) I don't know where (and if) we use `a.button` somewhere. But it's safer to keep it -- or check the whole code base for it and then remove it.

**Pull request merged**
