### PR TITLE
*add emblem feature

### PR DESCRIPTION
**Pull request by MarkusHiller**

### CODE REVIEW

**Comment by bornhaeusser** [comment]
got a failure

`Warning: require_once(/../utils/database.php): failed to open stream: No such file or directory in /volume1/web/game/opensoccer/controller/emblemController.php on line 3 Fatal error: require_once(): Failed opening required '/../utils/database.php' (include_path='.') in /volume1/web/game/opensoccer/controller/emblemController.php on line 3`

**Comment by MarkusHiller** [comment]
Have you checked that the file opensoccer/utils/database.php exists?

**Comment by bornhaeusser** [comment]
yes it works if i changed it to : 
require_once './config.php'; instead of /../
but also i have no menu entries and in the support site i could also not find the emblems...

**Comment by MarkusHiller** [comment]
every thing works but you dont have the option verein/einstellungen?

**Comment by bornhaeusser** [comment]
Ok now its there.

but:

`Notice: Use of undefined constant CONFIG_TABLE_PREFIX - assumed 'CONFIG_TABLE_PREFIX' in /volume1/web/game/opensoccer/controller/emblemController.php on line 34 Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /volume1/web/game/opensoccer/utils/database.php on line 23 Warning: mysql_result() expects parameter 1 to be resource, boolean given in /volume1/web/game/opensoccer/controller/emblemController.php on line 36`

**Comment by bornhaeusser** [comment]
could you give the db.file to update the data base

**Comment by MarkusHiller** [comment]
I have added this line:
define('CONFIG_TABLE_PREFIX', 'man_');
to config.php but i forgot to commit it.

you also need to add this tabel to your database:

CREATE TABLE `man_emblems` (
  `team` varchar(32) NOT NULL,
  `confirmed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`team`),
  UNIQUE KEY `team_UNIQUE` (`team`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by bornhaeusser** [comment]
ok thanks. last fail:

`Warning: move_uploaded_file(/volume1/web/game/opensoccer/controller./images/emblems/c81e728d9d4c2f636f067f89cc14862c.png): failed to open stream: No such file or directory in /volume1/web/game/opensoccer/controller/emblemController.php on line 74 Warning: move_uploaded_file(): Unable to move '/volume1/@tmp/php9o1VSC' to '/volume1/web/game/opensoccer/controller./images/emblems/c81e728d9d4c2f636f067f89cc14862c.png' in /volume1/web/game/opensoccer/controller/emblemController.php on line 74 Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /volume1/web/game/opensoccer/utils/database.php on line 23`

**Comment by MarkusHiller** [comment]
You have to give the folder images/emblems write rights (777)

**Comment by bornhaeusser** [comment]
the picture is in the folder.....

**Comment by bornhaeusser** [comment]
Tool is very very cool!!!

One more wish is in the Live Zentrale the Picture from Both playing Teams :-)

You Think that is possible to add this??

**Comment by MarkusHiller** [comment]
Thanks,
yes this is possible and will be added soon. Ther are some positions were we cann add the emblems. Please note that this pull request is closed and no changes will be added here. For futher changes please look at: https://github.com/MarkusHiller/OpenSoccer there is the new repo for www.opensoccer2.org

**Comment by bornhaeusser** [comment]
did alredy took this :-)

but could not open there some cases!

**Pull request closed without merging**
